# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  branches:
    include:
      - main
      - development

# By default, use self-hosted agents
pool: Default

# Opting out of pull request validation
pr: none

resources:
  repositories:
    # Azure DevOps repository
    - repository: <example-site>-pipelines
      type: git
      # project/repository
      name: <example-site>/<example-site>-pipelines

extends:
  template: azure-pipelines.yaml@<example-site>-pipelines
